import { MockStore, Voucher } from "@/types/voucher";

export const MOCK_STORES: MockStore[] = [
  { storeId: 1, storeName: "St. Martins Cafe - Main" },
  { storeId: 2, storeName: "St. Martins Cafe - Branch 2" },
  { storeId: 3, storeName: "St. Martins Cafe - Mall Kiosk" },
  { storeId: 4, storeName: "St. Martins Cafe - Downtown" },
];

export const MOCK_VOUCHERS: Voucher[] = [
  {
    voucherId: 1,
    voucherCode: "VCH-8K2N4Q",
    voucherName: "Anniversary Gift Card",
    voucherValueType: "fixed",
    voucherFixedValue: 500,
    voucherPercent: null,
    voucherMaxDiscount: null,
    voucherBalance: 500,
    voucherMaxUses: 1,
    voucherUsedCount: 0,
    voucherStatus: "active",
    voucherExpiresAt: "2026-12-31",
    voucherIsAllStores: true,
    voucherStoreIds: [],
    voucherIssuedTo: null,
    storeId: 1,
    voucherIssuedBy: "Aiken Canama",
    voucherRemarks: "Printed for anniversary promo batch",
    voucherCreatedAt: "2026-07-20T09:15:00",
  },
  {
    voucherId: 2,
    voucherCode: "VCH-2P9X7L",
    voucherName: "Loyalty 20% Off",
    voucherValueType: "percent",
    voucherFixedValue: null,
    voucherPercent: 20,
    voucherMaxDiscount: 200,
    voucherBalance: null,
    voucherMaxUses: 1,
    voucherUsedCount: 0,
    voucherStatus: "active",
    voucherExpiresAt: "2026-09-01",
    voucherIsAllStores: false,
    voucherStoreIds: [1, 3],
    voucherIssuedTo: "Maria Santos",
    storeId: 1,
    voucherIssuedBy: "Aiken Canama",
    voucherRemarks: null,
    voucherCreatedAt: "2026-07-18T14:32:00",
  },
  {
    voucherId: 3,
    voucherCode: "VCH-5T1D9R",
    voucherName: "Uncapped Staff Discount",
    voucherValueType: "percent",
    voucherFixedValue: null,
    voucherPercent: 15,
    voucherMaxDiscount: null,
    voucherBalance: null,
    voucherMaxUses: 5,
    voucherUsedCount: 2,
    voucherStatus: "active",
    voucherExpiresAt: null,
    voucherIsAllStores: true,
    voucherStoreIds: [],
    voucherIssuedTo: null,
    storeId: 2,
    voucherIssuedBy: "Aiken Canama",
    voucherRemarks: "Reusable up to 5 times",
    voucherCreatedAt: "2026-06-02T10:00:00",
  },
  {
    voucherId: 4,
    voucherCode: "VCH-9J3M6B",
    voucherName: "200 Store Credit",
    voucherValueType: "fixed",
    voucherFixedValue: 200,
    voucherPercent: null,
    voucherMaxDiscount: null,
    voucherBalance: 0,
    voucherMaxUses: 1,
    voucherUsedCount: 1,
    voucherStatus: "redeemed",
    voucherExpiresAt: "2026-08-01",
    voucherIsAllStores: false,
    voucherStoreIds: [4],
    voucherIssuedTo: "Carlo Reyes",
    storeId: 4,
    voucherIssuedBy: "Aiken Canama",
    voucherRemarks: null,
    voucherCreatedAt: "2026-05-15T11:20:00",
  },
  {
    voucherId: 5,
    voucherCode: "VCH-3F8H2W",
    voucherName: "Expired Promo",
    voucherValueType: "fixed",
    voucherFixedValue: 100,
    voucherPercent: null,
    voucherMaxDiscount: null,
    voucherBalance: 100,
    voucherMaxUses: 1,
    voucherUsedCount: 0,
    voucherStatus: "expired",
    voucherExpiresAt: "2026-06-30",
    voucherIsAllStores: true,
    voucherStoreIds: [],
    voucherIssuedTo: null,
    storeId: 1,
    voucherIssuedBy: "Aiken Canama",
    voucherRemarks: null,
    voucherCreatedAt: "2026-05-01T08:00:00",
  },
  {
    voucherId: 6,
    voucherCode: "VCH-7Q4Z1E",
    voucherName: "Voided Duplicate",
    voucherValueType: "percent",
    voucherFixedValue: null,
    voucherPercent: 10,
    voucherMaxDiscount: 50,
    voucherBalance: null,
    voucherMaxUses: 1,
    voucherUsedCount: 0,
    voucherStatus: "void",
    voucherExpiresAt: "2026-10-15",
    voucherIsAllStores: false,
    voucherStoreIds: [2],
    voucherIssuedTo: null,
    storeId: 2,
    voucherIssuedBy: "Aiken Canama",
    voucherRemarks: "Created twice by mistake, voided",
    voucherCreatedAt: "2026-07-10T16:45:00",
  },
];
